In [50]:
!pip install pandas_datareader

Collecting pandas_datareader
  Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
     ---------------------------------------- 0.0/109.5 kB ? eta -:--:--
     -------------------------------------- 109.5/109.5 kB 6.2 MB/s eta 0:00:00
Collecting lxml (from pandas_datareader)
  Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/31/58/e3b3dd6bb2ab7404f1f4992e2d0e6926ed40cef8ce1b3bbefd95877499e1/lxml-4.9.3-cp311-cp311-win_amd64.whl.metadata
  Downloading lxml-4.9.3-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: pandas>=0.23 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from pandas_datareader) (2.0.3)
Requirement already satisfied: requests>=2.19.0 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from pandas_datareader) (2.31.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from pandas>=0.23->pandas_datareader) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from pandas>=0.23->pandas_datareader) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from pandas>=0.23->pandas_datareader) (1.25.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2023.7.22)
Requirement already satisfied: six>=1.5 in c:\users\tis\documents\test\projects\python\edito\geo\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.16.0)
Downloading lxml-4.9.3-cp311-cp311-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -------- ------------------------------- 0.8/3.8 MB 25.4 MB/s eta 0:00:01
   --------------------- ------------------ 2.1/3.8 MB 26.3 MB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 29.2 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 24.1 MB/s eta 0:00:00
Installing collected packages: lxml, pandas_datareader
Successfully installed lxml-4.9.3 pandas_datareader-0.10.0

In [36]:
q = 'https://stats.oecd.org/restsdmx/sdmx.ashx/GetDataStructure/WEALTH'

In [51]:
import pandas as pd
import json
from urllib.request import urlopen
import datetime as dt
import pandas_datareader.data as web

In [52]:
response = urlopen(q).read()

In [57]:
start_time = dt.datetime(2015, 1, 1)
end_time = dt.datetime(2023, 1, 1)
df = web.DataReader('WEALTH', 'oecd', start_time, end_time)

In [58]:
df.tail()

Country                                               Australia  \
Variable   Mean financial assets per household (current prices)
Population                                     Total Population
Time
2015-01-01                                                NaN
2016-01-01                                                NaN
2017-01-01                                                NaN
2018-01-01                                                NaN
2019-01-01                                                NaN

Country                                                     \
Variable   Mean liabilities per household (current prices)
Population                                Total Population
Time
2015-01-01                                             NaN
2016-01-01                                             NaN
2017-01-01                                             NaN
2018-01-01                                             NaN
2019-01-01                                             NaN

Country                                                    \
Variable   Mean net wealth per household (current prices)
Population                               Total Population
Time
2015-01-01                                            NaN
2016-01-01                                            NaN
2017-01-01                                            NaN
2018-01-01                                            NaN
2019-01-01                                            NaN

Country                                                 \
Variable   Mean net wealth per person (current prices)
Population                            Total Population
Time
2015-01-01                                         NaN
2016-01-01                                         NaN
2017-01-01                                         NaN
2018-01-01                                         NaN
2019-01-01                                         NaN

Country                                                              \
Variable   Mean non-financial assets per household (current prices)
Population                                         Total Population
Time
2015-01-01                                                NaN
2016-01-01                                                NaN
2017-01-01                                                NaN
2018-01-01                                                NaN
2019-01-01                                                NaN

Country                                     \
Variable   Mean to median net wealth ratio
Population                Total Population
Time
2015-01-01                             NaN
2016-01-01                             NaN
2017-01-01                             NaN
2018-01-01                             NaN
2019-01-01                             NaN

Country                                                        \
Variable   Median debt-to-assets ratio of indebted households
Population                                   Total Population
Time
2015-01-01                                                NaN
2016-01-01                                                NaN
2017-01-01                                                NaN
2018-01-01                                                NaN
2019-01-01                                                NaN

Country                                                        \
Variable   Median debt-to-income ratio of indebted households
Population                                   Total Population
Time
2015-01-01                                                NaN
2016-01-01                                                NaN
2017-01-01                                                NaN
2018-01-01                                                NaN
2019-01-01                                                NaN

Country                                                                      \
Variable   Share of indebted households with debt-to-assets ratio above 75%
Population                                                 Total Population
Time
2015-01-01                                                NaN
2016-01-01                                                NaN
2017-01-01                                                NaN
2018-01-01                                                NaN
2019-01-01                                                NaN

Country                                  ...  \
Variable   Share of indebted households  ...
Population             Total Population  ...
Time                                     ...
2015-01-01                          NaN  ...
2016-01-01                          NaN  ...
2017-01-01                          NaN  ...
2018-01-01                          NaN  ...
2019-01-01                          NaN  ...

Country                                                         Lithuania  \
Variable   Share of indebted households with debt-to-income ratio above 3
Population                                               Total Population
Time
2015-01-01                                           19.00005
2016-01-01                                                NaN
2017-01-01                                                NaN
2018-01-01                                                NaN
2019-01-01                                                NaN

Country                                                          \
Variable   Share of top 1% of wealth Share of top 10% of wealth
Population          Total Population           Total Population
Time
2015-01-01                  14.84202                  47.889431
2016-01-01                       NaN                        NaN
2017-01-01                       NaN                        NaN
2018-01-01                       NaN                        NaN
2019-01-01                       NaN                        NaN

Country                               \
Variable   Share of top 5% of wealth
Population          Total Population
Time
2015-01-01                  36.02404
2016-01-01                       NaN
2017-01-01                       NaN
2018-01-01                       NaN
2019-01-01                       NaN

Country                                                      \
Variable   Median net wealth per household (current prices)
Population                                 Total Population
Time
2015-01-01                                          45880.0
2016-01-01                                              NaN
2017-01-01                                              NaN
2018-01-01                                              NaN
2019-01-01                                              NaN

Country                                                                                       \
Variable   Share of individuals with eq. liquid financial wealth <25% of income poverty line
Population                                                                  Total Population
Time
2015-01-01                                              62.27
2016-01-01                                                NaN
2017-01-01                                                NaN
2018-01-01                                                NaN
2019-01-01                                                NaN

Country                                                                                         \
Variable   Share of individuals with eq. liquid financial wealth <50 % of  income poverty line
Population                                                                    Total Population
Time
2015-01-01                                          72.889999
2016-01-01                                                NaN
2017-01-01                                                NaN
2018-01-01                                                NaN
2019-01-01                                                NaN

Country                                                                           \
Variable   Share of individuals with eq. net wealth < 25% of income poverty line
Population                                                      Total Population
Time
2015-01-01                                               3.84
2016-01-01                                                NaN
2017-01-01                                                NaN
2018-01-01                                                NaN
2019-01-01                                                NaN

Country                                                                            \
Variable   Share of individuals with eq. net wealth <50 % of  income poverty line
Population                                                       Total Population
Time
2015-01-01                                               4.31
2016-01-01                                                NaN
2017-01-01                                                NaN
2018-01-01                                                NaN
2019-01-01                                                NaN

Country
Variable   Share of bottom 40% of wealth
Population              Total Population
Time
2015-01-01                      8.826782
2016-01-01                           NaN
2017-01-01                           NaN
2018-01-01                           NaN
2019-01-01                           NaN

[5 rows x 580 columns]

In [59]:
df.columns

MultiIndex([('Australia', ...),
            ('Australia', ...),
            ('Australia', ...),
            ('Australia', ...),
            ('Australia', ...),
            ('Australia', ...),
            ('Australia', ...),
            ('Australia', ...),
            ('Australia', ...),
            ('Australia', ...),
            ...
            ('Lithuania', ...),
            ('Lithuania', ...),
            ('Lithuania', ...),
            ('Lithuania', ...),
            ('Lithuania', ...),
            ('Lithuania', ...),
            ('Lithuania', ...),
            ('Lithuania', ...),
            ('Lithuania', ...),
            ('Lithuania', ...)],
           names=['Country', 'Variable', 'Population'], length=580)

In [60]:
df.index

DatetimeIndex(['2015-01-01', '2016-01-01', '2017-01-01', '2018-01-01',
               '2019-01-01'],
              dtype='datetime64[ns]', name='Time', freq=None)

In [63]:
country = "Australia"
var = "Share of top 1% of wealth"  # Share of top 5% of wealth  # Median net wealth per household (current prices)
df_sgp_total = df[country][var]
df_sgp_total.head()

Population  Total Population
Time
2015-01-01               NaN
2016-01-01               NaN
2017-01-01               NaN
2018-01-01               NaN
2019-01-01               NaN